name: Pull Request validation

on: [pull_request]


jobs:
  AuctionX-contracts-ci:
    name: Run AuctionX-contracts validation
    uses: ./.github/workflows/AuctionX-contracts-ci.yaml

  AuctionX-frontend-ci:
    name: Run AuctionX-frontend validation
    uses: ./.github/workflows/AuctionX-frontend-ci.yaml

